version: '3.2'

services:
  reverse-proxy:
    image: traefik:latest
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp
      - ./scripts/traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
      - ./scripts:/helpers
      - ./scripts/add-cert.sh:/scripts/add-cert.sh
      - ./scripts/refresh-certs.sh:/scripts/refresh-certs.sh
    command: --api --docker --ping --web
    restart: always
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    labels:
      - traefik.frontend.rule=Host:monitor.the-uptons.com
      - traefik.port=8080
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    healthcheck:
      test: ["CMD", "/traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 5
