version: '3.2'

services:
  reverse-proxy:
    image: traefik:alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp
      - /dev/null:/traefik.toml
      - ./scripts:/helpers
      - ./scripts/add-cert.sh:/scripts/add-cert.sh
      - ./scripts/refresh-certs.sh:/scripts/refresh-certs.sh
    command: --api --docker --ping --logLevel=DEBUG --web
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: always
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 5
